[package]
name = "rot-common"
description = "Common code for the rot project"
license = "MIT"
repository = "github.com/skeptrunedev/rot"
readme = "../README.md"
keywords = ["rot", "common", "library"]
categories = ["development-tools::build-tools"]
version = "0.1.0"
edition = "2021"

[lints.clippy]
all = "deny"
pedantic = "deny"
nursery = "deny"
cargo = "deny"
unwrap_used = "deny"

[dependencies]
config = { version = "0.15.4", features = [
  "toml",
  "yaml",
  "json",
  "ini",
  "json5",
  "ron",
] }
serde = "1.0.217"
